import re
from random import choice

import colorful


prefixes = [
    ("Adal", "edle {}"),
    ("Adel", "edle {}"),
    ("Al", "edle {}"),
    ("Ans", "kühne {}"),
    ("Bald", "kühne {}"),
    ("Bern", "{} wie ein Bär"),
    ("Bert", "glänzende {}"),
    ("Burk", "schützende {}"),
    ("Burg", "schützende {}"),
    ("Chlod", "berühmte {}"),
    ("Klod", "berühmte {}"),
    ("Dago", "tägliche {}"),
    ("Dag", "tägliche {}"),
    ("Dank", "denkende {}"),
    ("Degen", "Degen-{}"),
    ("Eg", "Schwert-{}"),
    ("Ef", "Elfen-{}"),
    ("Eck", "Schwert-{}"),
    ("Det", "Volks-{}"),
    ("Diet", "Volks-{}"),
    ("Eber", "{} wie ein Eber"),
    ("Ed", "besitzende {}"),
    ("Ehren", "{} der Ehre"),
    ("Ehr", "ehrwürdige {}"),
    ("Er", "ehrwürdige {}"),
    ("E", "{} nach Recht und Gesetz"),
    ("Engel", "{} durch Engel"),
    ("Fol", "{} im Kriegsvolk"),
    ("Fried", "beschützende {}"),
    ("Friede", "beschützende {}"),
    ("Frith", "Friedens-{}"),
    ("Gang", "Kampf-{}"),
    ("Gari", "speerkämpfende {}"),
    ("Geb", "gebende {}"),
    ("Ger", "Speer-{}"),
    ("Gisel", "vornehme {}"),
    ("Gis", "geiselschützende {}"),
    ("Gode", "Gottes-{}"),
    ("God", "Gottes-{}"),
    ("Gott", "Gottes-{}"),
    ("Gund", "Kampf-{}"),
    ("Gun", "Kampf-{}"),
    ("Gust", "Kampf-{}"),
    ("Har", "Heeres-{}"),
    ("Hed", "starke {}"),
    ("Her", "Heeres-{}"),
    ("Hart", "starke {}"),
    ("Hel", "Schützen-{}"),
    ("Hil", "Schützen-{}"),
    ("Hild", "Schwert-{}"),
    ("Hilde", "Schwert-{}"),
    ("Hin", "Heim-{}"),
    ("Hein", "Heim-{}"),
    ("Hol", "{}"),
    ("Hu", "schlaue {}"),
    ("Hum", "riesige {}"),
    ("Kon", "kühne {}"),
    ("Kuni", "{}"),
    ("Ladis", "ruhmvolle {}"),
    ("Lam", "{}"),
    ("Lebe", "Volks-{}"),
    ("Leon", "{} im Kriegsvolk"),
    ("Lud", "ruhmvolle {}"),
    ("Mal", "gemeinsame {}"),  # in der Versammlung o_O
    ("Man", "männliche {}"),
    ("Mark", "Grenz-{}"),
    ("Mat", "mächtige {}"),
    ("Mar", "Kriegs-{}"),
    ("Mein", "mächtige {}"),
    ("Neid", "grimmige {}"),
    ("Neit", "grimmige {}"),
    ("Nik", "Volks-{}"),
    ("Niko", "Volks-{}"),
    ("Nor", "{} aus dem Norden"),
    ("Not", "{} in der Not"),
    ("Os", "Gottes-{}"),
    ("Ot", "{} der Heimat"),
    ("Or", "Schwert-{}"),
    ("Odil", "{} der Heimat"),
    ("Otto", "besitzende {}"),
    ("Rag", "kluge {}"),
    ("Ragn", "Kampf-{}"),
    ("Ram", "Raben-{}"),
    ("Rat", "beratende {}"),
    ("Rein", "beratende {}"),
    ("Ro", "ruhmvolle {}"),
    ("Rud", "ruhmreiche {}"),
    ("Ru", "ruhmreiche {}"),
    ("Rut", "ruhmreiche {}"),
    ("Sieg", "siegreiche {}"),
    ("Sig", "siegreiche {}"),
    ("Stanis", "beständige {}"),
    ("Ul", "gute {}"),
    ("Volk", "Volks-{}"),
    ("Wald", "herrschende {}"),
    ("Wal", "herrschende {}"),
    ("Wern", "warnende {}"),
    ("Widu", "{} des Waldes"),
    ("Wil", "willensstarke {}"),
    ("Wi", "kühne {}"),
    ("Win", "freundliche {}"),
    ("Wolde", "waltende {}"),
    ("Wolf", "Wolfs-{}"),
    ("Kriem", "{} im Helm"),
    ("Kuni", "{} für die Sippe"),
]

suffixes = {
    "Der": [
        ("bert", "Glänzende"),
        ("brecht", "Glänzende"),
        ("precht", "Glänzende"),
        ("fons", "Hilfsbereite"),
        ("fred", "Beschützer"),
        ("fried", "Beschützer"),
        ("win", "Freund"),
        ("uin", "Freund"),
        ("gand", "Kämpfer"),
        ("gar", "Speerkämpfer"),
        ("ger", "Speerkämpfer"),
        ("hard", "Starke"),
        ("hold", "Waltende"),
        ("ram", "Rabe"),
        ("wig", "Kämpfer"),
        ("mar", "Berühmte"),
        ("wart", "Wächter"),
        ("lef", "Lebende"),
        ("lev", "Lebende"),
        ("wald", "Herrscher"),
        ("ald", "Waltende"),
        ("rich", "König"),
        ("mont", "Schützer"),
        ("mund", "Gewaltige"),
        ("bald", "Mächtige"),
        ("mann", "Mann"),
        ("jof", "Fürst"),
        ("olf", "Wolf"),
        ("not", "Kampf"),
        ("lieb", "Sohn"),
        ("her", "Mann"),
        ("av", "Ordner"),
        ("ald", "Führer"),
        ("mut", "Kühne"),
        ("brand", "Kämpfer"),
        ("mar", "Berühmte"),
        ("rad", "Berater"),
        ("ard", "Berater"),
        ("laus", "Herrscher"),
        ("las", "Herrscher"),
        ("recht", "Glänzende"),
        ("pold", "Kühne"),
        ("kar", "Speer"),
        ("nar", "Held"),
        ("bod", "Gebietende"),
        ("urd", "Hüter"),
        ("bot", "Bote"),
    ],
    "Die": [
        ("gard", "Schützerin"),
        ("gund", "Kämpferin"),
        ("heid", "Geartete"),
        ("berta", "Glänzende"),
        ("mut", "Mutige"),
        ("ma", "Gebende"),
        ("rune", "Zauberin"),
        ("wine", "Freundin"),
        ("hild", "Kämpfende"),
        ("burga", "Schützerin"),
        ("mar", "Berühmte"),
        ("ke", "Herrin"),
        ("lind", "Schildträgerin"),
        ("linde", "Schildträgerin"),
        ("gunde", "Kämpferin"),
        ("traut", "Vertraute"),
        ("bett", "Geweihte"),
        ("erike", "Reiche"),
        ("rike", "Reiche"),
        ("nelda", "Bekämpferin"),
        ("run", "Verkündende"),
        ("trud", "Kämpferin"),
        ("sine", "Wissende"),
        ("wig", "Kämpferin"),
        ("burg", "Schützerin"),
        ("borg", "Geborgene"),
        ("rid", "Reiterin"),
        ("rina", "Reine"),
        ("trun", "Raunende"),
        ("hilde", "Kämpferin"),
        ("milla", "Volksnahe"),
        ("wiga", "Kämpferin"),
        ("munde", "Schützerin"),
    ]
}

colors = {"Der": colorful.red, "Die": colorful.green}

print("Wie wäre es mit einem dieser Namen?")
for _ in range(20):
    art = choice(["Der", "Die"])
    pre, fmt = choice(prefixes)
    post, fill = choice(suffixes[art])
    desc = re.sub("-(.)", lambda x: x.group(1).lower(), fmt.format(fill))
    print(colors[art]("{:<20}{:<27}".format(f"{pre}{post}", f"({art} {desc})")))
